#!/bin/bash
set -e

# Configuración por defecto (puedes sobrescribir en config/squeezelite.conf)
SL_NAME="${SL_NAME:-Lyrion DAC}"
SL_SOUNDCARD="${SL_SOUNDCARD:-default}"
SL_SERVER="${SL_SERVER:-127.0.0.1}"
SL_EXTRA_ARGS="${SL_EXTRA_ARGS:--b 500:2000 -C 5 -r 44100-192000}"

# Preferir valores del repo config si existen
if [ -f "config/squeezelite.conf" ]; then
  # shellcheck disable=SC1091
  source "config/squeezelite.conf"
fi

echo "Escribiendo /etc/default/squeezelite"
sudo tee /etc/default/squeezelite > /dev/null <<EOF
# Generated by LyrionMusicSetup
SL_NAME="${SL_NAME}"
SL_SOUNDCARD="${SL_SOUNDCARD}"
SL_SERVER="${SL_SERVER}"
SL_EXTRA_ARGS="${SL_EXTRA_ARGS}"
EOF

# Determinar usuario para el servicio
if id squeezelite &>/dev/null; then
  RUN_USER="squeezelite"
else
  RUN_USER="${LMS_USER:-lyrion}"
fi

# Crear unit systemd idempotente
SERVICE_PATH="/etc/systemd/system/squeezelite.service"
echo "Creando unit systemd en ${SERVICE_PATH}"
sudo tee "${SERVICE_PATH}" > /dev/null <<EOF
[Unit]
Description=Squeezelite - Lightweight SqueezePlayer
After=network.target sound.target

[Service]
Type=simple
User=${RUN_USER}
# Cargar /etc/default/squeezelite y ejecutar
ExecStart=/bin/sh -c '. /etc/default/squeezelite && exec /usr/bin/squeezelite -n "\$SL_NAME" -o "\$SL_SOUNDCARD" -s "\$SL_SERVER" \$SL_EXTRA_ARGS'
Restart=on-failure
RestartSec=2

[Install]
WantedBy=multi-user.target
EOF

# Recargar systemd, desmascarar, habilitar y arrancar
sudo systemctl daemon-reload
sudo systemctl unmask squeezelite.service 2>/dev/null || true
sudo systemctl enable --now squeezelite.service

echo "squeezelite.service habilitado y arrancado. Usa: sudo systemctl status squeezelite.service"